### ISSUE TITLE
Erro no campo CEP

### ISSUE THREAD

**Issue by DougM244** [lmtsufape/vida-agroecologica-gestao-web-v2#21]
Erro de formato inválido no CEP ao cadastrar nova associação, um novo usuário, e um novo usuário na rota pública.

**Comment by DougM244** [comment]
Resolvido o problema ao cadastrar nova associação :white_check_mark:

**Comment by nettojulio** [comment]
Encerrada devido à ausência de detalhes técnicos e comentários sugerirem que foi sanado o erro.
